"""The Alembic migrations must match backend/db/models.py and round-trip.

Runs against a temp-file SQLite DB (sa.Enum degrades to VARCHAR there), so no
live Postgres is needed in CI.
"""

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

from backend.db.seed import REPO_ROOT


@pytest.fixture
def alembic_cfg(tmp_path, monkeypatch):
    url = f"sqlite+pysqlite:///{tmp_path / 'm.db'}"
    monkeypatch.setenv("DATABASE_URL", url)
    cfg = Config(str(REPO_ROOT / "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg, url


def test_upgrade_creates_every_table(alembic_cfg):
    cfg, url = alembic_cfg
    command.upgrade(cfg, "head")
    tables = set(inspect(create_engine(url)).get_table_names())
    assert {"words", "users", "review_logs", "sessions"} <= tables


def test_no_drift_between_migrations_and_models(alembic_cfg):
    cfg, _ = alembic_cfg
    command.upgrade(cfg, "head")
    # Raises AutogenerateDiffsDetected if models.py and the migrations disagree.
    command.check(cfg)


def test_downgrade_to_base_is_clean(alembic_cfg):
    cfg, url = alembic_cfg
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    tables = set(inspect(create_engine(url)).get_table_names())
    assert tables <= {"alembic_version"}
