"""Generate backend/data/seed.sql from the ingestion build output.

Pipeline:
    python -m backend.data.ingest_frequency  --sample
    python -m backend.data.ingest_wiktionary --sample
    python -m backend.data.build_seed

seed.sql is committed (docker-compose mounts it as a Postgres init script). The
DDL section is kept in sync with backend/db/models.py by hand until a migration
tool is wired in (CLAUDE.md section 4: backend/db/migrations/).
"""

from __future__ import annotations

import json
from pathlib import Path

from backend.data.assign_cefr import assign_cefr

BUILD_DIR = Path(__file__).parent / "build"
SEED_PATH = Path(__file__).parent / "seed.sql"

DDL = """\
-- GENERATED by backend/data/build_seed.py -- do not edit the INSERT section by hand.
-- DDL mirrors backend/db/models.py (CLAUDE.md section 5).

CREATE TYPE cefr_level   AS ENUM ('A1', 'A2', 'B1', 'B2');
CREATE TYPE user_target  AS ENUM ('work', 'travel', 'general', 'exam');
CREATE TYPE review_source AS ENUM ('review', 'new');

CREATE TABLE IF NOT EXISTS words (
    id               SERIAL PRIMARY KEY,
    lemma            VARCHAR(128) NOT NULL UNIQUE,
    article          VARCHAR(8),
    plural           VARCHAR(128),
    translation_en   VARCHAR(256) NOT NULL,
    cefr_level       cefr_level   NOT NULL,
    frequency_rank   INTEGER      NOT NULL,
    topic            VARCHAR(64),
    ipa_or_audio_ref TEXT
);
CREATE INDEX IF NOT EXISTS ix_words_cefr_level     ON words (cefr_level);
CREATE INDEX IF NOT EXISTS ix_words_frequency_rank ON words (frequency_rank);
CREATE INDEX IF NOT EXISTS ix_words_topic          ON words (topic);

CREATE TABLE IF NOT EXISTS users (
    id         SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    target     user_target NOT NULL DEFAULT 'general'
);

CREATE TABLE IF NOT EXISTS review_logs (
    id               SERIAL PRIMARY KEY,
    user_id          INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    word_id          INTEGER     NOT NULL REFERENCES words (id) ON DELETE CASCADE,
    timestamp        TIMESTAMPTZ NOT NULL DEFAULT now(),
    correct          BOOLEAN     NOT NULL,
    response_time_ms INTEGER     NOT NULL,
    source           review_source NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_review_logs_user_id   ON review_logs (user_id);
CREATE INDEX IF NOT EXISTS ix_review_logs_word_id   ON review_logs (word_id);
CREATE INDEX IF NOT EXISTS ix_review_logs_timestamp ON review_logs (timestamp);

CREATE TABLE IF NOT EXISTS sessions (
    id                         SERIAL PRIMARY KEY,
    user_id                    INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    started_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    duration_minutes_requested INTEGER     NOT NULL,
    words_covered              INTEGER     NOT NULL DEFAULT 0,
    topic                      VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS ix_sessions_user_id ON sessions (user_id);
"""


def _sql_str(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def build() -> str:
    words_path = BUILD_DIR / "words.jsonl"
    if not words_path.exists():
        raise SystemExit(
            f"missing {words_path}; run ingest_frequency.py --sample then "
            "ingest_wiktionary.py --sample first"
        )

    rows: list[str] = []
    skipped_out_of_scope = 0
    for line in words_path.read_text(encoding="utf-8").splitlines():
        rec = json.loads(line)
        cefr = assign_cefr(rec["frequency_rank"])
        if cefr is None:  # rank > 4000: out of A1-B2 scope (section 6)
            skipped_out_of_scope += 1
            continue
        rows.append(
            "  ("
            f"{_sql_str(rec['lemma'])}, {_sql_str(rec.get('article'))}, "
            f"{_sql_str(rec.get('plural'))}, {_sql_str(rec['translation_en'])}, "
            f"'{cefr}', {rec['frequency_rank']}, {_sql_str(rec.get('topic'))}, "
            f"{_sql_str(rec.get('ipa_or_audio_ref'))})"
        )

    parts = [
        DDL,
        "\nINSERT INTO words",
        "  (lemma, article, plural, translation_en, cefr_level, "
        "frequency_rank, topic, ipa_or_audio_ref)",
        "VALUES",
    ]
    parts.append(",\n".join(rows) + "\nON CONFLICT (lemma) DO NOTHING;\n")
    parts.append("\n-- A demo learner so the API and MCP layers have something to point at.\n")
    parts.append("INSERT INTO users (id, target) VALUES (1, 'work') ON CONFLICT DO NOTHING;\n")
    if skipped_out_of_scope:
        parts.append(f"\n-- {skipped_out_of_scope} lemma(s) skipped: frequency_rank > 4000.\n")
    return "\n".join(parts)


def main() -> None:
    SEED_PATH.write_text(build(), encoding="utf-8")
    print(f"wrote {SEED_PATH}")


if __name__ == "__main__":
    main()
