"""Generate backend/data/seed.sql (DATA only) from the ingestion build output.

Pipeline:
    python -m backend.data.ingest_frequency  [--sample | --source leipzig ...]
    python -m backend.data.ingest_wiktionary [--sample | --kaikki ...]
    python -m backend.data.build_seed

Schema is owned by Alembic (backend/db/migrations/), NOT by this file. seed.sql
is pure INSERTs and is applied after `alembic upgrade head` -- see
`python -m backend.db.seed`. It is committed; the raw/derived corpora are not.

Each row gets an approximate CEFR level (assign_cefr) and an approximate topic
(assign_topic) -- both documented as approximations (CLAUDE.md section 6).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from backend.data.assign_cefr import assign_cefr
from backend.data.assign_topic import assign_topic

BUILD_DIR = Path(__file__).parent / "build"
SEED_PATH = Path(__file__).parent / "seed.sql"

# Frequency-ranked corpora are dominated at the top by function words and
# inflected surface forms whose only "gloss" is a grammatical description
# ("nominative/accusative singular feminine", "third-person singular present of
# sein", "contraction of in + dem"). Those make useless flashcards, so drop any
# word whose translation reads as grammar rather than meaning.
_GRAMMATICAL_GLOSS = re.compile(r"""(?ix)
      ^\s*(inflection|gerund|conjugation|declension)\s+of\b
    | \b(nominative|genitive|dative|accusative|vocative)\b
    | \b(singular|plural)\s+of\b
    | \b(contraction|separated\s+form|alternative\s+(form|spelling))\s+of\b
    | \bpronominal\s+adverb\s+of\b
    | \b(comparative|superlative)\s+(degree|form)\s+of\b
    | \brefers?\s+to\s+(a\s+|an\s+)?(neuter|masculine|feminine|noun|person|animal|thing|abstract)
    | \b(first|second|third)[-\s]person\b
    | ^\s*(reflexive|personal|possessive|demonstrative|relative|indefinite)\s+pronoun\b
    | ^\s*(substantival\s+)?possessive\b
    | ^\s*(definite|indefinite)\s+article\b
    """)


def is_grammatical_gloss(translation_en: str) -> bool:
    return bool(_GRAMMATICAL_GLOSS.search(translation_en or ""))


# Closed-class function words: articles, pronouns, contractions, auxiliaries and
# the most basic particles. A learner absorbs these implicitly, and the
# frequency corpus + first-Wiktionary-gloss combination makes terrible cards for
# them ("auf -> open", "einen -> to unite"). Excluded from the study vocabulary;
# they still appear in the full corpus if you re-derive without this filter.
_FUNCTION_WORDS = frozenset("""
    der die das den dem des ein eine einen einem einer eines
    ich du er sie es wir ihr mich dich sich uns euch mir dir ihm ihn ihnen
    mein meine dein deine sein seine ihre unser euer
    und oder aber denn sondern
    in an auf zu mit von bei nach aus um vor über unter durch für gegen ohne
    am im zum zur beim vom ins ans
    ist sind war waren bin bist sei seid wird werden wurde wurden worden
    hat habe haben hatte hatten
    kann können konnte muss müssen musste soll sollen wollte will
    nicht kein keine keinen nichts nie
    ja nein doch schon noch nur auch so man
    als wie wenn dass weil da dann hier dort
    dieser diese dieses jener welche welcher was wer wo warum
    """.split())  # noqa: SIM905 -- a readable block, not an 80-item list literal


def is_function_word(lemma: str) -> bool:
    return lemma.lower() in _FUNCTION_WORDS


HEADER = (
    "-- GENERATED by backend/data/build_seed.py -- do not hand-edit.\n"
    "-- DATA only. Run `alembic upgrade head` first (schema lives in "
    "backend/db/migrations/).\n"
)

COLUMNS = (
    "(lemma, article, plural, translation_en, cefr_level, frequency_rank, topic, ipa_or_audio_ref)"
)


def _sql_str(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def build() -> str:
    words_path = BUILD_DIR / "words.jsonl"
    if not words_path.exists():
        raise SystemExit(f"missing {words_path}; run ingest_frequency then ingest_wiktionary first")

    rows: list[str] = []
    skipped_out_of_scope = 0
    skipped_grammatical = 0
    skipped_function = 0
    topic_hits = 0
    for line in words_path.read_text(encoding="utf-8").splitlines():
        rec = json.loads(line)
        cefr = assign_cefr(rec["frequency_rank"])
        if cefr is None:  # rank > 4000: out of A1-B2 scope (section 6)
            skipped_out_of_scope += 1
            continue
        if is_function_word(rec["lemma"]):
            skipped_function += 1
            continue
        if is_grammatical_gloss(rec.get("translation_en", "")):
            skipped_grammatical += 1
            continue
        topic = rec.get("topic") or assign_topic(rec.get("translation_en"), rec.get("lemma"))
        if topic:
            topic_hits += 1
        rows.append(
            "  ("
            f"{_sql_str(rec['lemma'])}, {_sql_str(rec.get('article'))}, "
            f"{_sql_str(rec.get('plural'))}, {_sql_str(rec['translation_en'])}, "
            f"'{cefr}', {rec['frequency_rank']}, {_sql_str(topic)}, "
            f"{_sql_str(rec.get('ipa_or_audio_ref'))})"
        )

    parts = [
        HEADER,
        f"INSERT INTO words\n  {COLUMNS}\nVALUES",
        ",\n".join(rows) + "\nON CONFLICT (lemma) DO NOTHING;\n",
        "-- A demo learner (id 1 on a fresh DB) so the API/MCP layers have a target.",
        "INSERT INTO users (target) SELECT 'work' " "WHERE NOT EXISTS (SELECT 1 FROM users);",
        "",
        f"-- {len(rows)} words, {topic_hits} topic-tagged. Skipped: "
        f"{skipped_out_of_scope} (rank > 4000), {skipped_function} (function word), "
        f"{skipped_grammatical} (grammatical gloss).",
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    SEED_PATH.write_text(build(), encoding="utf-8")
    print(f"wrote {SEED_PATH}")


if __name__ == "__main__":
    main()
