"""Generate backend/data/seed.sql (DATA only) from the ingestion build output.

Pipeline:
    python -m backend.data.ingest_frequency  [--sample | --source leipzig ...]
    python -m backend.data.ingest_wiktionary [--sample | --kaikki ...]
    python -m backend.data.build_seed

Schema is owned by Alembic (backend/db/migrations/), NOT by this file. seed.sql
is pure INSERTs and is applied after `alembic upgrade head` -- see
`python -m backend.db.seed`. It is committed; the raw/derived corpora are not.

Each row gets an approximate CEFR level (assign_cefr) and an approximate topic
(assign_topic) -- both documented as approximations.
"""

from __future__ import annotations

import json
import re
from collections.abc import Iterable, Iterator
from pathlib import Path

from backend.data.assign_cefr import assign_cefr
from backend.data.assign_topic import assign_topic

BUILD_DIR = Path(__file__).parent / "build"
SEED_PATH = Path(__file__).parent / "seed.sql"

# Frequency-ranked corpora are dominated at the top by function words and
# inflected surface forms whose only "gloss" is a grammatical description
# ("nominative/accusative singular feminine", "third-person singular present of
# sein", "contraction of in + dem"). Those make useless flashcards, so drop any
# word whose translation reads as grammar rather than meaning.
_GRAMMATICAL_GLOSS = re.compile(r"""(?ix)
      ^\s*(inflection|gerund|conjugation|declension)\s+of\b
    | \b(nominative|genitive|dative|accusative|vocative)\b
    | \b(singular|plural)\s+of\b
    | \b(contraction|separated\s+form|alternative\s+(form|spelling))\s+of\b
    | \bpronominal\s+adverb\s+of\b
    | \b(comparative|superlative)\s+(degree|form)\s+of\b
    | \brefers?\s+to\s+(a\s+|an\s+)?(neuter|masculine|feminine|noun|person|animal|thing|abstract)
    | \b(first|second|third)[-\s]person\b
    | ^\s*(reflexive|personal|possessive|demonstrative|relative|indefinite)\s+pronoun\b
    | ^\s*(substantival\s+)?possessive\b
    | ^\s*(definite|indefinite)\s+article\b
    """)


def is_grammatical_gloss(translation_en: str) -> bool:
    return bool(_GRAMMATICAL_GLOSS.search(translation_en or ""))


# Closed-class function words: articles, pronouns, contractions, auxiliaries and
# the most basic particles. A learner absorbs these implicitly, and the
# frequency corpus + first-Wiktionary-gloss combination makes terrible cards for
# them ("auf -> open", "einen -> to unite"). Excluded from the study vocabulary;
# they still appear in the full corpus if you re-derive without this filter.
_FUNCTION_WORDS = frozenset("""
    der die das den dem des ein eine einen einem einer eines
    ich du er sie es wir ihr mich dich sich uns euch mir dir ihm ihn ihnen
    mein meine dein deine sein seine ihre unser euer
    und oder aber denn sondern
    in an auf zu mit von bei nach aus um vor über unter durch für gegen ohne
    am im zum zur beim vom ins ans
    ist sind war waren bin bist sei seid wird werden wurde wurden worden
    hat habe haben hatte hatten
    kann können konnte muss müssen musste soll sollen wollte will
    nicht kein keine keinen nichts nie
    ja nein doch schon noch nur auch so man
    als wie wenn dass weil da dann hier dort
    dieser diese dieses jener welche welcher was wer wo warum
    """.split())  # noqa: SIM905 -- a readable block, not an 80-item list literal


def is_function_word(lemma: str) -> bool:
    return lemma.lower() in _FUNCTION_WORDS


HEADER = (
    "-- GENERATED by backend/data/build_seed.py -- do not hand-edit.\n"
    "-- DATA only. Run `alembic upgrade head` first (schema lives in "
    "backend/db/migrations/).\n"
)

# Fixed scrypt hash of the password "demo" (see backend/api/security.py). A
# committed seed can't use a random salt, so the demo login uses this constant.
# It is a throwaway fixture credential, not a secret.
DEMO_PW_HASH = (
    "scrypt$16384$8$1$2e6fe4056da89da43570bd3bd3b7a6c2$"
    "6003f793b1948c2161289eea192d84f8abc791b4428d97d675b90f2621bfda11"
)

COLUMNS = (
    "(lemma, article, plural, translation_en, cefr_level, frequency_rank, topic, ipa_or_audio_ref)"
)


def _sql_str(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def is_study_word(rec: dict) -> bool:
    """A record worth putting on a flashcard: not a function word, not a bare
    grammatical inflection."""
    return not (
        is_function_word(rec["lemma"]) or is_grammatical_gloss(rec.get("translation_en", ""))
    )


def iter_study_words(records: Iterable[dict]) -> Iterator[tuple[dict, str]]:
    """Yield ``(record, cefr_level)`` for each keepable word, in input order.

    ``records`` must be frequency-ordered. CEFR is assigned from the word's rank
    *among study words* -- i.e. after function/grammatical entries are dropped --
    so "A1" means "the ~500 most frequent words actually worth learning", not
    "the top 500 corpus tokens" (which are mostly der/die/und/ist/...). Stops at
    the first word past the B2 boundary; everything rarer is out of scope.
    """
    study_rank = 0
    for rec in records:
        if not is_study_word(rec):
            continue
        study_rank += 1
        cefr = assign_cefr(study_rank)
        if cefr is None:
            return
        yield rec, cefr


def build() -> str:
    words_path = BUILD_DIR / "words.jsonl"
    if not words_path.exists():
        raise SystemExit(f"missing {words_path}; run ingest_frequency then ingest_wiktionary first")

    records = [json.loads(line) for line in words_path.read_text(encoding="utf-8").splitlines()]
    skipped_function = sum(1 for r in records if is_function_word(r["lemma"]))
    skipped_grammatical = sum(
        1
        for r in records
        if not is_function_word(r["lemma"]) and is_grammatical_gloss(r.get("translation_en", ""))
    )

    rows: list[str] = []
    topic_hits = 0
    for rec, cefr in iter_study_words(records):
        topic = rec.get("topic") or assign_topic(rec.get("translation_en"), rec.get("lemma"))
        if topic:
            topic_hits += 1
        rows.append(
            "  ("
            f"{_sql_str(rec['lemma'])}, {_sql_str(rec.get('article'))}, "
            f"{_sql_str(rec.get('plural'))}, {_sql_str(rec['translation_en'])}, "
            f"'{cefr}', {rec['frequency_rank']}, {_sql_str(topic)}, "
            f"{_sql_str(rec.get('ipa_or_audio_ref'))})"
        )

    skipped_out_of_scope = len(records) - skipped_function - skipped_grammatical - len(rows)
    parts = [
        HEADER,
        f"INSERT INTO words\n  {COLUMNS}\nVALUES",
        ",\n".join(rows) + "\nON CONFLICT (lemma) DO NOTHING;\n",
        "-- A demo learner (id 1 on a fresh DB) so the API/MCP layers have a target.",
        "-- Login: username 'demo', password 'demo' (fixed scrypt hash -- demo fixture only).",
        "INSERT INTO users (target, username, password_hash)\n"
        f"  SELECT 'work', 'demo', '{DEMO_PW_HASH}'\n"
        "  WHERE NOT EXISTS (SELECT 1 FROM users);",
        "",
        f"-- {len(rows)} study words (CEFR by post-filter rank), {topic_hits} topic-tagged. "
        f"Dropped: {skipped_function} function words, {skipped_grammatical} grammatical entries, "
        f"{skipped_out_of_scope} past the B2 boundary.",
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    SEED_PATH.write_text(build(), encoding="utf-8")
    print(f"wrote {SEED_PATH}")


if __name__ == "__main__":
    main()
