-- GENERATED by backend/data/build_seed.py -- do not edit the INSERT section by hand.
-- DDL mirrors backend/db/models.py (CLAUDE.md section 5).

CREATE TYPE cefr_level   AS ENUM ('A1', 'A2', 'B1', 'B2');
CREATE TYPE user_target  AS ENUM ('work', 'travel', 'general', 'exam');
CREATE TYPE review_source AS ENUM ('review', 'new');

CREATE TABLE IF NOT EXISTS words (
    id               SERIAL PRIMARY KEY,
    lemma            VARCHAR(128) NOT NULL UNIQUE,
    article          VARCHAR(8),
    plural           VARCHAR(128),
    translation_en   VARCHAR(256) NOT NULL,
    cefr_level       cefr_level   NOT NULL,
    frequency_rank   INTEGER      NOT NULL,
    topic            VARCHAR(64),
    ipa_or_audio_ref TEXT
);
CREATE INDEX IF NOT EXISTS ix_words_cefr_level     ON words (cefr_level);
CREATE INDEX IF NOT EXISTS ix_words_frequency_rank ON words (frequency_rank);
CREATE INDEX IF NOT EXISTS ix_words_topic          ON words (topic);

CREATE TABLE IF NOT EXISTS users (
    id         SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    target     user_target NOT NULL DEFAULT 'general'
);

CREATE TABLE IF NOT EXISTS review_logs (
    id               SERIAL PRIMARY KEY,
    user_id          INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    word_id          INTEGER     NOT NULL REFERENCES words (id) ON DELETE CASCADE,
    timestamp        TIMESTAMPTZ NOT NULL DEFAULT now(),
    correct          BOOLEAN     NOT NULL,
    response_time_ms INTEGER     NOT NULL,
    source           review_source NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_review_logs_user_id   ON review_logs (user_id);
CREATE INDEX IF NOT EXISTS ix_review_logs_word_id   ON review_logs (word_id);
CREATE INDEX IF NOT EXISTS ix_review_logs_timestamp ON review_logs (timestamp);

CREATE TABLE IF NOT EXISTS sessions (
    id                         SERIAL PRIMARY KEY,
    user_id                    INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    started_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
    duration_minutes_requested INTEGER     NOT NULL,
    words_covered              INTEGER     NOT NULL DEFAULT 0,
    topic                      VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS ix_sessions_user_id ON sessions (user_id);


INSERT INTO words
  (lemma, article, plural, translation_en, cefr_level, frequency_rank, topic, ipa_or_audio_ref)
VALUES
  ('Haus', 'das', 'Häuser', 'house', 'A1', 51, NULL, 'haʊ̯s'),
  ('Frau', 'die', 'Frauen', 'woman; Mrs', 'A1', 52, NULL, 'fʁaʊ̯'),
  ('Mann', 'der', 'Männer', 'man', 'A1', 53, NULL, 'man'),
  ('Kind', 'das', 'Kinder', 'child', 'A1', 54, NULL, 'kɪnt'),
  ('Jahr', 'das', 'Jahre', 'year', 'A1', 55, NULL, 'jaːɐ̯'),
  ('Tag', 'der', 'Tage', 'day', 'A1', 56, NULL, 'taːk'),
  ('Zeit', 'die', 'Zeiten', 'time', 'A1', 57, NULL, 't͡saɪ̯t'),
  ('Hand', 'die', 'Hände', 'hand', 'A1', 58, NULL, 'hant'),
  ('Auge', 'das', 'Augen', 'eye', 'A1', 59, NULL, 'ˈaʊ̯ɡə'),
  ('Woche', 'die', 'Wochen', 'week', 'A1', 60, NULL, 'ˈvɔxə'),
  ('Wasser', 'das', 'Wasser', 'water', 'A1', 61, NULL, 'ˈvasɐ'),
  ('Stadt', 'die', 'Städte', 'city', 'A1', 62, NULL, 'ʃtat'),
  ('Land', 'das', 'Länder', 'country; land', 'A1', 63, NULL, 'lant'),
  ('Arbeit', 'die', 'Arbeiten', 'work', 'A1', 64, NULL, 'ˈaʁbaɪ̯t'),
  ('Leben', 'das', 'Leben', 'life', 'A1', 65, NULL, 'ˈleːbn̩'),
  ('Freund', 'der', 'Freunde', 'friend', 'A1', 66, NULL, 'fʁɔɪ̯nt'),
  ('Schule', 'die', 'Schulen', 'school', 'A1', 67, NULL, 'ˈʃuːlə'),
  ('Buch', 'das', 'Bücher', 'book', 'A1', 68, NULL, 'buːx'),
  ('Tisch', 'der', 'Tische', 'table', 'A1', 69, NULL, 'tɪʃ'),
  ('Tür', 'die', 'Türen', 'door', 'A1', 70, NULL, 'tyːɐ̯'),
  ('gehen', NULL, NULL, 'to go', 'A1', 71, NULL, 'ˈɡeːən'),
  ('kommen', NULL, NULL, 'to come', 'A1', 72, NULL, 'ˈkɔmən'),
  ('machen', NULL, NULL, 'to do; make', 'A1', 73, NULL, 'ˈmaxn̩'),
  ('sagen', NULL, NULL, 'to say', 'A1', 74, NULL, 'ˈzaːɡn̩'),
  ('sehen', NULL, NULL, 'to see', 'A1', 75, NULL, 'ˈzeːən'),
  ('geben', NULL, NULL, 'to give', 'A1', 76, NULL, 'ˈɡeːbn̩'),
  ('finden', NULL, NULL, 'to find', 'A1', 77, NULL, 'ˈfɪndn̩'),
  ('denken', NULL, NULL, 'to think', 'A1', 78, NULL, 'ˈdɛŋkn̩'),
  ('essen', NULL, NULL, 'to eat', 'A1', 79, NULL, 'ˈɛsn̩'),
  ('trinken', NULL, NULL, 'to drink', 'A1', 80, NULL, 'ˈtʁɪŋkn̩'),
  ('gut', NULL, NULL, 'good', 'A1', 81, NULL, 'ɡuːt'),
  ('groß', NULL, NULL, 'big; tall', 'A1', 82, NULL, 'ɡʁoːs'),
  ('klein', NULL, NULL, 'small', 'A1', 83, NULL, 'klaɪ̯n'),
  ('neu', NULL, NULL, 'new', 'A1', 84, NULL, 'nɔɪ̯'),
  ('alt', NULL, NULL, 'old', 'A1', 85, NULL, 'alt'),
  ('jung', NULL, NULL, 'young', 'A1', 86, NULL, 'jʊŋ'),
  ('schnell', NULL, NULL, 'fast', 'A1', 87, NULL, 'ʃnɛl'),
  ('langsam', NULL, NULL, 'slow', 'A1', 88, NULL, 'ˈlaŋzaːm'),
  ('schön', NULL, NULL, 'beautiful; nice', 'A1', 89, NULL, 'ʃøːn'),
  ('wichtig', NULL, NULL, 'important', 'A1', 90, NULL, 'ˈvɪçtɪç')
ON CONFLICT (lemma) DO NOTHING;


-- A demo learner so the API and MCP layers have something to point at.

INSERT INTO users (id, target) VALUES (1, 'work') ON CONFLICT DO NOTHING;
